In [1]:
level1=540000*0.05
level2=(1210000-540000)*0.12
level3=(2420000-1210000)*0.2
level4=(4530000-2420000)*0.3
income=int(input('請輸入淨年所得額:'))
if income<=540000:
    tax=income*0.05
elif income<=1210000:
    tax=level1+((income-540000)*0.12)
elif income<=2420000:
    tax=level1+level2+((income-1210000)*0.2)
elif income<=4530000:
    tax=level1+level2+level3+((income-2420000)*0.3)
else:
    tax=ievel1+level2+level3+level4+((income-4530000)*0.4)
print('應繳稅額=',tax)

請輸入淨年所得額: 100000


應繳稅額= 5000.0


In [3]:
import sympy as sp
x=sp.Symbol('x')
sp.integrate(sp.sin(3*x),x)
from scipy.integrate import quad
import numpy as np
def f(x):
    return np.exp(-x)*np.sin(3*x)
i=quad(f,0,2*np.pi)
print(i[0])

0.29943976718048754


In [5]:
import numpy as np
A=np.array([[1,-2,-1],[2,2,-1],[-1,-1,2]])
print(A)
B=np.array([6,1,1])
H=np.linalg.solve(A,B)
print(H)

[[ 1 -2 -1]
 [ 2  2 -1]
 [-1 -1  2]]
[ 3. -2.  1.]


In [2]:
import os
print(os.getcwd())  # 顯示當前工作目錄

C:\Users\user
